import numpy as np

print('__ '*10)
print('1d array')
print(np.random.ranf(size=2))
print('__ '*10)
print('2d array')
print(np.random.ranf(size=(2,3)))
print('__ '*10)
print('3d array')
print(np.random.ranf(size=(3,3,2)))
print('__ '*10)
print(np.random.ranf((3,3,2)))
print('__ '*10)
print(np.random.random((4,3,2)))
print('__ '*10)
print(np.random.random())
print(np.random.random_sample())
print(np.random.sample())
print('__ '*10)
print(np.random.random_integers(low=0, high=5, size=4))
print(np.random.random_integers(1,6,(2,2,3)))
print(np.random.randint(low=0, high=5, size=4))
print(np.random.randint(2, 10, (2, 3, 4)))